name: tail_app
description: A Cross Platform Tail Control App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.2.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.0
  cross_platform: ^3.0.1
  flutter_riverpod: ^2.4.10
  logging: ^1.2.0
  logging_flutter: ^3.0.0
  flutter_reactive_ble: ^5.3.1
  go_router: ^13.2.0
  double_back_to_close_app: ^2.1.0
  pedometer: ^4.0.1
  proximity_sensor: ^1.0.4
  simple_circular_progress_bar: ^1.0.2
  shake: ^2.2.0
  flex_color_scheme: ^7.3.1
  flutter_joystick: ^0.0.4
  sentry_flutter: ^7.16.1
  sentry_logging: ^7.16.1
  sentry_hive: ^7.16.1
  sentry_dio: ^7.16.1
  vector_math: ^2.1.4
  collection: ^1.18.0
  flutter_foreground_service: ^0.4.1
  upgrader: ^9.0.0
  chart_sparkline: ^1.0.15+1
  package_info_plus: ^5.0.1
  multi_value_listenable_builder: ^0.0.2
  feedback_sentry: ^3.0.0
  flutter_android_volume_keydown: ^1.0.0
  intl: #pinned to flutter version
  url_launcher: ^6.2.4
  open_settings: ^2.0.2
  flutter_colorpicker: ^1.0.3
  flutter_adaptive_scaffold: ^0.1.7+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  plausible_analytics: ^0.3.0
  fk_user_agent: ^2.1.0
  flutter_nearby_connections: ^1.1.2
  dio: ^5.4.1
  json_serializable: ^6.7.1
  crypto: ^3.0.3
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:
  custom_lint: 0.5.11
  riverpod_lint:
  riverpod_generator:
  flutter_native_splash: ^2.3.10
  riverpod_annotation: ^2.3.4
  sentry_dart_plugin: ^1.7.1
  intl_translation:
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  generate: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false
  project: 'tail-app'
  org: 'sentry'
  #auth_token: ...
  url: 'https://sentry.codel1417.xyz'