name: tail_app
description: A Cross Platform Tail Control App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: https://github.com/Codel1417/tail_app
environment:
  sdk: ^3.2.3

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.1
  cross_platform: ^3.0.1
  flutter_riverpod: ^2.5.1
  logging: ^1.2.0
  logging_flutter: ^3.0.0
  flutter_reactive_ble: ^5.3.1
  go_router: ^13.2.2
  pedometer: ^4.0.1
  proximity_sensor: ^1.1.0
  shake: ^2.2.0
  flex_color_scheme: ^7.3.1
  flutter_joystick: ^0.0.4
  sentry_flutter: ^7.18.0
  sentry_logging: ^7.18.0
  sentry_hive: ^7.18.0
  sentry_dio: ^7.18.0
  vector_math: ^2.1.4
  collection: ^1.18.0
  flutter_foreground_service: ^0.4.1
  upgrader: ^10.0.1
  chart_sparkline: ^1.0.15+1
  package_info_plus: ^5.0.1
  multi_value_listenable_builder: ^0.0.2
  feedback_sentry: ^3.0.0
  flutter_android_volume_keydown: ^1.0.0
  intl: #pinned to flutter version
  url_launcher: ^6.2.5
  open_settings: ^2.0.2
  flex_color_picker: ^3.4.1
  flutter_adaptive_scaffold: ^0.1.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  plausible_analytics: ^0.3.0
  flutter_nearby_connections: ^1.1.2
  dio: ^5.4.2+1
  json_serializable: ^6.7.1
  crypto: ^3.0.3
  animate_do: ^3.3.4
  fl_chart: ^0.67.0
  file_picker: ^8.0.0+1
  wakelock_plus: ^1.1.4
  pod_player: ^0.2.1
  tivy: ^0.1.1
  pdfx: ^2.6.0
  flutter_app_badger: ^1.5.0
  in_app_review: ^2.0.9
  install_referrer: ^1.2.1
  circular_buffer: ^0.11.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  fluttertoast: ^8.2.4
  flutter_screen_lock: ^9.0.2
  back_button_interceptor: ^7.0.3
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:
  custom_lint: ^0.6.4
  riverpod_lint:
  riverpod_generator:
  flutter_native_splash: ^2.4.0
  riverpod_annotation: ^2.3.5
  sentry_dart_plugin: ^1.7.1
  intl_translation:
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  icons_launcher: ^2.1.7
  pretty_dio_logger: ^1.3.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/tailcostickers/tgs/
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false

icons_launcher:
  image_path: "assets/copilot_fox_icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: '#0573a4'
      adaptive_foreground_image: "assets/copilot_fox_icon.png"
    ios:
      enable: true

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # IMPORTANT NOTE: These parameter do not affect the configuration of Android 12 and later, which
  # handle splash screens differently that prior versions of Android.  Android 12 and later must be
  # configured specifically in the android_12 section below.

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#0573a4"
  color_dark: "#0573a4"
  android_12:
    color: "#0573a4"
    color_dark: "#0573a4"