name: tail_app
description: A Cross Platform Tail Control App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  wakelock: ^0.6.2
  cross_platform: ^3.0.1
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  disable_battery_optimization: ^1.1.0+1
  logging_flutter: ^2.0.1
  flutter_reactive_ble: ^5.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
flutter:
  uses-material-design: true