name: tail_app
description: A Cross Platform Tail Control App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: https://github.com/Codel1417/tail_app
environment:
  sdk: ^3.2.3

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.1
  cross_platform: ^3.0.1
  flutter_riverpod: ^2.5.1
  logging: ^1.2.0
  flutter_reactive_ble: ^5.3.1
  go_router: ^14.0.2
  vector_math: ^2.1.4 # used for joystick
  collection: ^1.18.0
  flutter_foreground_service: # Needs gradle namespace
    git:
      url: https://github.com/cph-cachet/flutter-plugins
      path: packages/flutter_foreground_service
  package_info_plus: ^8.0.0
  intl: #pinned to flutter version
  url_launcher: ^6.2.6
  app_settings: ^5.1.1

  path_provider: ^2.1.3
  uuid: ^4.4.0
  plausible_analytics: ^0.3.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  crypto: ^3.0.3 # used for md5 hash checking during ota download
  file_picker: ^8.0.3 # used to manually select firmware file
  wakelock_plus: ^1.2.5
  #pod_player: ^0.2.2
  #tivy: ^0.1.1

  circular_buffer: ^0.11.0  # Used for serial console
  fluttertoast: ^8.2.5
  back_button_interceptor: ^7.0.3 # for rejecting the back button in some places due to flutter/Go Router bugs
  riverpod_annotation: ^2.3.5
  device_info_plus: ^9.0.3
  install_referrer: # Needs gradle namespace
    git:
      url: https://github.com/undreeyyy/flutter_plugin_install_referrer
      ref: fd87e9b8f0d5ed909e929388244456f72b9b63c7

  # Widgets / UI
  flutter_screen_lock: ^9.0.2 # used to hide dev mode toggle
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  flex_color_picker: ^3.4.1
  flutter_adaptive_scaffold: ^0.1.10+2
  animate_do: ^3.3.4
  fl_chart: ^0.67.0
  chart_sparkline: ^1.0.15+1 # used for the move easing visual
  flex_color_scheme: ^7.3.1
  pdfx: ^2.6.0
  flutter_joystick: ^0.0.4
  multi_value_listenable_builder: ^0.0.2
  multi_listenable_builder: ^1.0.0
  logging_flutter: ^3.0.0


  # Dio HTTP
  dio: ^5.4.3+1
  native_dio_adapter: ^1.3.0

  # Sensors
  pedometer: # Needs gradle namespace
    git:
      url: https://github.com/cph-cachet/flutter-plugins
      path: packages/pedometer
  proximity_sensor: # Needs gradle namespace
    git:
      url: https://github.com/Codel1417/flutter-proximity-sensor-plugin
  sensors_plus: ^5.0.1
  shake: # Needs gradle namespace
    git:
      url: https://github.com/Codel1417/shake
      ref: dieringe
  flutter_android_volume_keydown: # Needs gradle namespace
    git:
      url: https://github.com/Codel1417/flutter_android_volume_keydown
      ref: feature/media_button

  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # play services
  in_app_review: ^2.0.9
  upgrader: ^10.3.0

  # Spicy
  firebase_messaging: ^14.9.1

  # Sentry
  sentry_flutter: ^7.20.1
  sentry_logging: ^7.20.0
  sentry_hive: ^7.20.0
  sentry_dio: ^7.20.0
  feedback_sentry: ^3.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:
  custom_lint: ^0.6.4
  riverpod_lint:
  riverpod_generator:
  flutter_native_splash: ^2.4.0
  sentry_dart_plugin: ^2.0.0
  intl_translation:
  hive_generator: ^2.0.1
  icons_launcher: ^2.1.7
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/tailcostickers/tgs/
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false

icons_launcher:
  image_path: "assets/copilot_fox_icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: '#0573a4'
      adaptive_foreground_image: "assets/copilot_fox_icon.png"
    ios:
      enable: true

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # IMPORTANT NOTE: These parameter do not affect the configuration of Android 12 and later, which
  # handle splash screens differently that prior versions of Android.  Android 12 and later must be
  # configured specifically in the android_12 section below.

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#0573a4"
  color_dark: "#0573a4"
  android_12:
    color: "#0573a4"
    color_dark: "#0573a4"