name: tail_app
description: A Cross Platform Tail Control App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.2.3
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.2.0
  wakelock:
  cross_platform: ^3.0.1
  flutter_riverpod: ^2.4.9
  logging: ^1.2.0
  logging_flutter: ^3.0.0
  flutter_reactive_ble: ^5.2.0
  shared_preferences: ^2.2.2
  go_router: ^13.0.1
  double_back_to_close_app: ^2.1.0
  pedometer: ^4.0.1
  proximity_sensor: ^1.0.4
  simple_circular_progress_bar: ^1.0.2
  shake: ^2.2.0
  haptic_feedback: ^0.4.2
  adaptive_theme: ^3.5.0
  side_sheet_material3: ^0.0.2
  flutter_joystick: ^0.0.4
  introduction_screen: ^3.1.12
  sentry_flutter: ^7.15.0
  sentry_logging: ^7.15.0
  vector_math: ^2.1.4
  collection: ^1.18.0
  flutter_foreground_service: ^0.4.1
  upgrader: ^9.0.0
  flutter_json_view: ^1.1.4
  chart_sparkline: ^1.0.15+1
  dynamic_color: ^1.6.9
  package_info_plus: ^5.0.1
  multi_value_listenable_builder: ^0.0.2
  feedback_sentry: ^3.0.0
  flutter_android_volume_keydown: ^1.0.0
  intl:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:
  custom_lint:
  riverpod_lint:
  riverpod_generator:
  flutter_gen: ^5.4.0
  flutter_native_splash: ^2.3.9
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  sentry_dart_plugin: ^1.6.3
  intl_translation:
flutter:
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false
  project: ...
  org: ...
  auth_token: ...
  url: ...
  wait_for_processing: false
  commits: auto
  ignore_missing: true