on:
  push:
  pull_request:

jobs:
  build_android:
    name: Build Android Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          cache: true
      - name: Update Build Number
        run: bash ${GITHUB_WORKSPACE}/Scripts/update_version.sh
        working-directory: Scripts
      - name: Install packages
        run: flutter config --no-cli-animations && flutter pub get
      - name: Generate localizations
        run: flutter gen-l10n
      - name: Generate configs
        run: dart run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/Frontend/intnDefs.dart lib/l10n/*.arb && flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        run: flutter build apk --split-per-abi
      - name: Build App Bundle
        run: flutter build appbundle
      - uses: actions/upload-artifact@v4
        with:
          path: |
            build/app/outputs/apk
            build/app/outputs/bundle
          compression-level: 0 # bundles are already compressed
      - name: read pubspec
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_action_js
        with:
          config: ./pubspec.yaml

      - name: Upload debug symbols
        run: flutter packages pub run sentry_dart_plugin
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_RELEASE: ${{ steps.read_action_js.outputs['version'] }}
#      - name: Create Sentry release
#        uses: getsentry/action-release@v1
#        env:
#          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
#          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
#          SENTRY_URL: ${{ secrets.SENTRY_URL }}
#        with:
#          version: ${{ steps.read_action_js.outputs['version'] }}
