on:
  workflow_dispatch:

jobs:
  build_ios:
    name: Build IOS Artifact
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - name: Install packages
        run: flutter pub get
      - name: Generate localizations
        run: flutter gen-l10n
      - name: Generate configs
        run: dart run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/Frontend/intnDefs.dart lib/l10n/*.arb && flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build app
        run: flutter build ipa --release --no-codesign
      - name: Upload debug symbols
        run: flutter packages pub run sentry_dart_plugin

