on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - master
  pull_request:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      pull-requests: read
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    name: Build
    runs-on: ${{ matrix.os }}
    outputs:
      SENTRY_RELEASE: ${{ steps.build.outputs.SENTRY_RELEASE }}
      SENTRY_DIST: ${{ steps.build.outputs.SENTRY_DIST }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Environment
        uses: ./.github/actions/setup_build
      - name: Pre Build Tasks
        uses: ./.github/actions/pre_build
      - name: get Version
        id: version
        uses: ./.github/actions/version
        with:
            RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: Run build script
        id: build
        run: bash ${GITHUB_WORKSPACE}/Scripts/launchBuild.sh
        working-directory: Scripts
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          OS: ${{ matrix.os }}
          ANDROID_KEY_JKS: ${{ secrets.ANDROID_KEY_JKS }}
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
      - uses: actions/upload-artifact@v4
        continue-on-error: true
        if: matrix.os == 'ubuntu-latest'
        with:
          name: artifact-${{ matrix.os }}
          path: |
            build/app/outputs/apk
            build/app/outputs/bundle
      - name: Upload Beta
        if: github.event_name == 'push' && matrix.os == 'macos-latest'
        run: bash ${GITHUB_WORKSPACE}/Scripts/fastlane.sh
        working-directory: Scripts
        continue-on-error: false
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          BUILD_NUMBER: ${{ steps.version.outputs.BUILD_NUMBER }}
          GOOGLE_SECRETS: ${{ secrets.GOOGLE_PLAY }}
          APPLE_SECRETS: ${{ secrets.APPLE }}
          OS: ${{ matrix.os }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.FASTLANE_GITHUB }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      - name: Upload debug symbols
        run: dart pub global activate sentry_dart_plugin && dart pub global run sentry_dart_plugin
        if: github.event_name == 'push'
        continue-on-error: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_RELEASE: ${{ steps.build.outputs.VERSION }}
          SENTRY_DIST: ${{ steps.build.outputs.BUILD_NUMBER }}
