on:
  push:
    paths:
      - 'lib/Frontend/intnDefs.dart'
jobs:
  build_android:
    name: Update Localization Files
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          cache: true
      - name: Install packages
        run: flutter config --no-cli-animations && flutter pub get
      - name: Generate intl_translation
        run: dart run intl_translation:extract_to_arb --locale=en --output-file='./lib/l10n/messages_en.arb' ./lib/Frontend/intnDefs.dart
      - name: Stage Changes
        run: git config user.email "github-actions[bot]@users.noreply.github.com" && git config user.name "github-actions[bot]" && git add lib/l10n/messages_en.arb && 	git config --global --add safe.directory /github/workspace
      - name: Push
        uses: actions-x/commit@v2
        with:
          message: Update prebuilt binaries
          token: ${{ secrets.GITHUB_TOKEN }}