name: Run layerlens.

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - 'pubspec.yml'
      - 'pubspec.lock'
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: clone the repo
      uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
        cache: true

    - name: dart pub get
      run: flutter pub get

    - name: generate
      run: flutter pub run layerlens

    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update dependency diagrams.
